### ISSUE TITLE
대회 진출 기록을 하나만 표시하는 기능 수정 필요해요.

### ISSUE THREAD

**Issue by malkoG** [HI-ARC/hi-arc.github.io#19]
대회 진출 기록 페이지를 보시면 알겠지만, 
`competition/list.yaml` 파일에 아래와 같이 지금까지 참가했던 대회를 나열하고 있는데요. 각각의 대회에 대한 기록은 하위 디렉토리 result에 각각에 대한 정보가 기록되어 있습니다. 
```yaml
- year: 2016
  lists:
  - name: "삼성 대학생 프로그래밍 대회"

- year: 2017
  lists:
  - name: "ACM-ICPC Daejeon Region"

- year: 2018
  lists:
  - name: "ACM-ICPC Seoul Region"
  - name: "UCPC 예선"
  - name: "카카오 Coding Festival"
  - name: "이데일리 CODING CHALLENGE"
```
`result` 디렉토리의 yaml 파일을 하나 들여다보면 한 팀에 대한 정보만 기록할 수 있게 되어있네요. 한 팀만 참여했던 것처럼 보일 수도 있으니, 비록 성적이 저조했더라도 모든 기록을 투명하게 공개할 수 있어야 한다고 생각합니다. 의도했던 것이 아닐 수도 있으니, 구조적인 논의가 필요하면 시간내서 한번 논의를 해봅시다. 

```yaml
year: 2018
competition: "ACM-ICPC Seoul Region"
result: "Honorable mention"

team: "bye-arc 팀"
members: ["김민균(2기)", "김형석(2기)", "유지혁(3기)"]

picture: "icpc_1280x720.jpg"
```
